package org.aston.ecommerce.report;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import org.aston.ecommerce.user.CustomUserDetails;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Date;

public class ReportGenerator {
    private final CustomUserDetails currUser;
    private final Font headerFont = new Font(Font.FontFamily.HELVETICA, 16);
    private final Font secondHeaderFont = new Font(Font.FontFamily.HELVETICA, 14);
    private final Font subFont = new Font(Font.FontFamily.HELVETICA, 11);
    private final Font subFontBold = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);

    public ReportGenerator(CustomUserDetails currUser){
        this.currUser = currUser;
    }


    public void export(HttpServletResponse response) throws IOException, DocumentException {
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, response.getOutputStream());
        document.open();
        this.addMetaData(document);
        this.addTitlePage(document);
        document.close();
    }


    private void addTitlePage(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        // Empty line
        this.addEmptyLine(preface, 1);
        // Write the header
        preface.add(new Paragraph("PC Labs Admin Report", headerFont));
        this.addEmptyLine(preface, 1);
        preface.add(new Paragraph(
                "Report generated by: " + this.currUser.getActualUsernameNotEmail() + ", " + new Date(),
                subFontBold));

        document.add(preface);
        // Start a new page
        document.newPage();
    }

    private void addMetaData(Document document){
        document.addTitle("PC Labs Admin Report");
        document.addSubject("Admin Report");
        document.addAuthor("Group 22");
        document.addCreator("Group 22");
    }

    private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

}
